services:
  app:
    image: fme-workbench-2022:22343
    build:
      context: .
      args:
        - TIME_ZONE_AREA=Americas
        - TIME_ZONE_LOCATION=Denver
        - USER=kweller
        - FME_DESKTOP_BUILD_VERSION=0.0.2.22343
    environment:
      - DISPLAY=${DISPLAY}
    logging:
      driver: journald
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - opt:/opt/fme-desktop-2022
      - type: bind
        source: /home/${USER}
        target: /home/${USER}
    network_mode: host
volumes:
  opt: