services:
  app:
    image: modgeosys/fme-workbench-2022:22343
    container_name: fme-workbench-2022
    build:
      context: .
      args:
        - TIME_ZONE_AREA=Americas
        - TIME_ZONE_LOCATION=Denver
        - USER=${USER}
        - FME_DESKTOP_BUILD_VERSION=0.0.2.22343
    environment:
      - DISPLAY=${DISPLAY}
    logging:
      driver: journald
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - opt_2022:/opt/fme-desktop-2022
      - type: bind
        source: ${HOME}
        target: ${HOME}
    network_mode: host
volumes:
  opt_2022: